### ISSUE TITLE
[add] 開発環境の整備

### ISSUE THREAD

**Issue by manabuyasuda** [csstalk/website#1]
- Pug（一部JSONでデータを管理したい）
- PostCSS（import以外はcssnext、Atomic designの手法を取り入れてみたい）
- JS ES2016（Bebel）。JQueryを使ってもいい。
- アイコンフォント（Gulpで生成）
- Aigis（スタイルガイドはPugで書く）

**Comment by matsuoshi** [comment]
@manabuyasuda ありがとうございます〜
めっちゃしっかり出来あがってますね…！

ひとまず npm install 〜 gulpが動作するところまで確認できました、
細かいところは実際開発はじまってから何か出てくるかも？ですが
1点だけ、 `npm run default` について、スクリプト名を `default` ではなく `start` にするのが一般的かと思います
(npmの仕様で、 `npm run start` は `npm start` と省略して書ける、というものがあり、それを使うのが多いイメージ)
ご検討お願いします〜

https://docs.npmjs.com/misc/scripts

**Comment by manabuyasuda** [comment]
@matsuoshi 
ありがとうございます。
スクリプト名を変更しました。 
`npm start`が一般的なんですね。たまに見かけたんですけど、どういう位置付けで使えばいいのかなと思っていました。

Gulpでjsの連結をするパッケージのことを忘れてましたが、開発をはじめてから検証できたらと思います。
